export const imovel = [
    {
        cidade: "Guanambi",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg"
    },
    {
        cidade: "Caetité",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg"    },
    {
        cidade: "Salvador",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg"    },
    {
        cidade: "Brumado",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg" },
    {
        cidade: "Irecê",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg"},
    {
        cidade: "Vitória da Conquista",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg" },
    {
        cidade: "João Dourado",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg"},
    {
        cidade: "Brasilândia",
        bairro: "Monte Pascoal",
        rua: "Rua 7 de Setembro",
        numero: "77",
        tipoDeImovel: "Casa",
        tipoDeNegocio: "Aluguel",
        atualDisponibilidade: "Disponível",
        telefoneContato: "5465498894",
        dataAnuncio: "11/12/2023",
        imagemImovel: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Casa_Amarela.jpg"
    }

]